name: 'Update Fork Action'
description: 'Updates your repo from the fork'
author: 'doshyt'
inputs: 
  GithubToken:
    description: 'Personal Access Token'
  Origin:
    description: 'Origin repo URL'
  Upstream:
    description: 'Upstream repo URL'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GithubToken }}
    - ${{ inputs.Origin }}
    - ${{ inputs.Upstream }}
